### ISSUE TITLE
Is This Same As SvelteKit's Built-in CSP and CSRF

### ISSUE THREAD

**Issue by barziahmed** [svelte-u/sveltekit-security#1]
Hello,

SvelteKit provides [configuration](https://kit.svelte.dev/docs/configuration) for enabling and making use of CSP and CSRF. So, what does this plugin provide that SvelteKit doesn't have? 

I'm a bit new to CSP headers and etc. I'm sorry if my question is confusing.

Thank you.

**Comment by Mohamed-Kaizen** [comment]
Hi there, I understand your confusion. While SvelteKit offers CSP and CSRF configuration, this plugin actually focuses on different aspects of security.

This plugin doesn't directly handle CSP or CSRF, but it provides valuable tools for setting other important security headers and utilities to enhance your application's protection.

**Comment by barziahmed** [comment]
That's interesting. One more question please. In your plugin, you use [universal hooks](https://kit.svelte.dev/docs/hooks#universal-hooks), instead of server hooks, is there any security benefit to using universal hooks for security headers instead of server hooks?

**Comment by Mohamed-Kaizen** [comment]
That's intriguing! Could you point me to where I used "universal hooks" in the plugin code? While I was building it, I primarily used "hooks.server.js/ts," which refers to server-side hooks.

**Comment by barziahmed** [comment]
[Here](https://github.com/svelte-u/sveltekit-security/blob/main/src/hooks.ts) is the file.

**Comment by Mohamed-Kaizen** [comment]
The file `hooks.ts` is merely a name; it doesn’t impact SvelteKit. I used it primarily for organizing the project and identifying the location from which the main functions of the project are exposed.

**Comment by barziahmed** [comment]
Understood. I'm sorry just one last question if you don't mind, 
Will there be docs for this project (sveltekit-security)? In the [website](https://svelte-u.vercel.app/) I coudn't find the section specific security...

**Comment by Mohamed-Kaizen** [comment]
I've been heads-down in some Vue projects lately, so adding new features and docs for this package has been on hold. But fear not! I'm eager to jump back in soon. In the meantime, I'd love to see your contributions via pull requests.
